INSERT INTO PRODUCT (PRICE,PRODUCT_CATEGORY,PRODUCT_DESCRIPTION,PRODUCT_NAME,STOCK) VALUES (499.99,'Games console','Games','PS5', 10),(399.99,'Games console','Games','XBOX X', 10);
INSERT INTO ADDRESS (CITY,COUNTRY,POSTCODE,STREET) VALUES ('London','UK','W1 5ju','123 London Road'),('Wales','UK','sh33 eap','123 sheep Road');
INSERT INTO CUSTOMER (EMAIL,FIRST_NAME,SECOND_NAME,ADDRESS_ID) VALUES ('abc@gmail.com','vinesh','ghela',1),('shaun_sheep@gmail.com','shaun','sheep',2);
INSERT INTO ORDERS (DATE,NOTES,TOTAL_PRICE,CUSTOMER_ID,PAID) VALUES ('2021-03-16','None',499.00,1, true),('2021-03-16','None',399.00,2, false);
INSERT INTO ORDER_LINE (ORDER_ID,PRODUCT_ID) VALUES (1,1), (1,1),(1,2),(2,1),(2,2);
